CREATE TABLE accounts(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL ,
    mobile VARCHAR(11) NOT NULL,
    userType VARCHAR(255) NOT NULL DEFAULT'customer',
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    createdAt DATETIME,
    updatedAt DATETIME,
    deletedAT DATETIME
);

CREATE TABLE category(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL ,
    slug VARCHAR(255) NOT NULL
);

CREATE TABLE products(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL ,
    description VARCHAR(255) NOT NULL,
    qty VARCHAR(255) NOT NULL,
    image INT NOT NULL,
    price DOUBLE NOT NULL,
    createdAt DATETIME,
    updatedAt DATETIME,
    deletedAT DATETIME
);